#!/usr/bin/env node
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SCAN_DIR = join(ROOT, 'app')
const OUTPUT = join(ROOT, 'app/assets/kun-icons.ts')

const SCAN_EXT = new Set(['.vue', '.ts', '.tsx', '.js', '.mjs'])
const SKIP = new Set(['node_modules', '.nuxt', '.output', 'dist', '.git'])
const ICON_PATTERN =
  /["']([a-z][a-z0-9-]{1,30}):([a-z0-9][a-z0-9-]{0,60})["']/g
const COLLECTIONS = new Set(['lucide'])

async function* walk(dir) {
  let entries
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch {
    return
  }
  for (const e of entries) {
    if (SKIP.has(e.name)) continue
    const full = join(dir, e.name)
    if (e.isDirectory()) yield* walk(full)
    else if (e.isFile()) {
      const dot = e.name.lastIndexOf('.')
      if (dot >= 0 && SCAN_EXT.has(e.name.slice(dot))) yield full
    }
  }
}

const collectionCache = new Map()
const loadCollection = (c) => {
  if (collectionCache.has(c)) return collectionCache.get(c)
  let data = null
  try {
    const p = require.resolve(`@iconify-json/${c}/icons.json`)
    data = JSON.parse(readFileSync(p, 'utf8'))
  } catch {
    data = null
  }
  collectionCache.set(c, data)
  return data
}

const main = async () => {
  const wanted = new Set()
  for await (const file of walk(SCAN_DIR)) {
    const content = await readFile(file, 'utf8')
    for (const match of content.matchAll(ICON_PATTERN)) {
      const [, collection, icon] = match
      if (/^\d+$/.test(icon)) continue
      if (COLLECTIONS.has(collection)) wanted.add(`${collection}:${icon}`)
    }
  }

  const names = [...wanted].sort()
  const entries = []
  const missing = []
  for (const name of names) {
    const [collection, icon] = name.split(':')
    const set = loadCollection(collection)
    const def = set?.icons?.[icon]
    if (!def || typeof def.body !== 'string') {
      missing.push(name)
      continue
    }
    const w = def.width ?? set.width
    const h = def.height ?? set.height
    entries.push({ name, body: def.body, w, h })
  }

  const lines = entries.map(({ name, body, w, h }) => {
    const extra =
      (w && w !== 24 ? `, width: ${w}` : '') +
      (h && h !== 24 ? `, height: ${h}` : '')
    return `  ${JSON.stringify(name)}: { body: ${JSON.stringify(body)}${extra} }`
  })

  const out = `/**
 * Auto-generated by scripts/generate-icons.mjs — do not edit by hand.
 * Run \`pnpm --filter web icons\` after changing icon usage.
 */
import type { KunIconData } from '@kungal/ui-core'

export const KUN_ICONS: Record<string, KunIconData> = {
${lines.join(',\n')}
}
`
  await mkdir(dirname(OUTPUT), { recursive: true })
  await writeFile(OUTPUT, out)
  console.log(`Wrote ${entries.length} icons → app/assets/kun-icons.ts`)
  if (missing.length) {
    console.warn(
      `${missing.length} icon(s) not found:\n  ${missing.join(', ')}`
    )
  }
}

main().catch((err) => {
  console.error(err)
  process.exitCode = 1
})
